<a href="https://colab.research.google.com/github/AmirJlr/LLMs/blob/master/01_Intro_to_transformers_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q transformers

In [2]:
from transformers import pipeline

### Simple `pipline`

In [4]:
classifier = pipeline("sentiment-analysis", device='cuda')

classifier("We are very happy that are madridista!")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda


[{'label': 'POSITIVE', 'score': 0.9998414516448975}]

### Sentence ==> Tokenize ==> Model

## Use separate `Tokenizer` and  `Model`

In [5]:
from transformers import AutoTokenizer, AutoModel

In [6]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

model = AutoModel.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [7]:
txt = "We are very happy that are madridista!"
inp = tokenizer(txt, return_tensors="pt") # Pytorch tensor
inp

{'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2008,  2024,  6921, 11921,   999,
           102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [10]:
out = model(**inp)

print(out)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.0522,  0.2609,  0.2627,  ..., -0.8328,  0.6995,  0.2456],
         [ 0.2927, -0.0678,  0.0855,  ..., -1.1793,  1.3962, -0.3133],
         [ 0.2167,  0.0057,  0.2807,  ..., -1.2055,  0.2960,  0.2429],
         ...,
         [-0.3701, -0.0366,  0.2322,  ..., -1.2067,  0.1227, -0.3386],
         [-0.0020,  0.0704, -0.1523,  ...,  0.1388,  0.4593, -0.2784],
         [ 0.7049,  0.1713, -0.1471,  ...,  0.0396, -0.6545, -0.3123]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.9048, -0.5552, -0.9768,  0.8752,  0.7536, -0.2483,  0.9148,  0.4097,
         -0.9232, -1.0000, -0.5282,  0.9484,  0.9706,  0.8464,  0.9492, -0.8104,
         -0.3539, -0.6679,  0.5072, -0.4718,  0.8418,  1.0000, -0.1333,  0.5008,
          0.5629,  0.9900, -0.8625,  0.9374,  0.9549,  0.6685, -0.8438,  0.2239,
         -0.9887, -0.3646, -0.9906, -0.9889,  0.5385, -0.6832, -0.1776, -0.0700,
         -0.9218,  0.4055,  1.00

## TensorFlow Based

In [12]:
from transformers import AutoTokenizer, TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = TFAutoModel.from_pretrained("bert-base-uncased")

inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")
outputs = model(**inputs)
outputs

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
array([[[-0.1143712 ,  0.19371381,  0.12495911, ..., -0.38269114,
          0.21065898,  0.54070807],
        [ 0.5308238 ,  0.32074872,  0.36645937, ..., -0.00360657,
          0.75785965,  0.03884354],
        [-0.4876513 ,  0.88492495,  0.425564  , ..., -0.6976217 ,
          0.445834  ,  0.12309374],
        ...,
        [-0.7002788 , -0.18150681,  0.329696  , ..., -0.48379302,
          0.06802312,  0.89008445],
        [-1.0354623 , -0.25667757, -0.03165276, ...,  0.31974334,
          0.39990234,  0.17954715],
        [ 0.607992  ,  0.2609703 , -0.31307214, ...,  0.03109776,
         -0.6282717 , -0.19942486]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-7.19458520e-01, -2.14449644e-01, -2.95760572e-01,
         3.66029859e-01,  2.79677778e-01,  2.21832972e-02,
         5.72991431e-01,  6.23313375e-02,  5.95860295e-0

## Customize pipeline

In [13]:
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "distilbert-base-uncased-finetuned-sst-2-english"

model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

results = classifier(["We are very happy that are madridista!",
                      "I dont like him."])

for result in results:
    print(result)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cuda:0


{'label': 'POSITIVE', 'score': 0.9998414516448975}
{'label': 'NEGATIVE', 'score': 0.997093677520752}


## More Deeper in Outputs

In [20]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

txt = "We are very happy to show you the Transformers library."

tokens = tokenizer.tokenize(txt)
token_ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = tokenizer(txt) # add first token


print (f' Tokens: {tokens}')
print("\n \n")

print (f'Token IDs: {token_ids}')
print("\n \n")

print (f'Input IDs: {input_ids}')

 Tokens: ['we', 'are', 'very', 'happy', 'to', 'show', 'you', 'the', 'transformers', 'library', '.']

 

Token IDs: [2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 19081, 3075, 1012]

 

Input IDs: {'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 19081, 3075, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [16]:
X_train = ["We are very happy to show you the Transformers library.",
            "We hope you don't hate it."]

batch = tokenizer(X_train, padding=True, truncation=True,
                   max_length=512, return_tensors="pt") # apply padding for smaller sentence tokens

print(batch)

{'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996, 19081,
          3075,  1012,   102],
        [  101,  2057,  3246,  2017,  2123,  1005,  1056,  5223,  2009,  1012,
           102,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}


## More Deep in Pytorch Model

In [19]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import torch.nn.functional as F

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

X_train = ["We are very happy to show you the Transformers library.",
            "We hope you don't hate it."]

batch = tokenizer(X_train, padding=True, truncation=True,
                   max_length=512, return_tensors="pt")

print("Input Batch: ", batch)
print("\n \n")

with torch.no_grad():
    outputs = model(**batch)
    print("Outputs: ", outputs)
    print("\n \n")

    predictions = F.softmax(outputs.logits, dim=1)
    print("Predictions: ", predictions)
    print("\n \n")

    labels = torch.argmax(predictions, dim=1) # get indice of max value
    print("Labels: ", labels)
    print("\n \n")

    labels = [model.config.id2label[label_id] for label_id in labels.tolist()]
    print("Final Label: ", labels)

Input Batch:  {'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996, 19081,
          3075,  1012,   102],
        [  101,  2057,  3246,  2017,  2123,  1005,  1056,  5223,  2009,  1012,
           102,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}

 

Outputs:  SequenceClassifierOutput(loss=None, logits=tensor([[-4.1329,  4.3811],
        [ 0.0818, -0.0418]]), hidden_states=None, attentions=None)

 

Predictions:  tensor([[2.0060e-04, 9.9980e-01],
        [5.3086e-01, 4.6914e-01]])

 

Labels:  tensor([1, 0])

 

Final Label:  ['POSITIVE', 'NEGATIVE']
